version: '3.1'

services:

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: GAud4mZby8F3SD6P
      MYSQL_DATABASE: createVM
      MYSQL_USER: useradmin
      MYSQL_PASSWORD: salvepauluk1

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: useradmin
      WORDPRESS_DB_PASSWORD: salvepauluk1
      WORDPRESS_DB_NAME: createVM

volumes:
  db_data:
